#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp

# Check if less than 4 parameters are passed, display usage and exit
if [ "$#" -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign parameters to variables
path_to_file="$1"
ip="$2"
username="$3"
ssh_key="$4"

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username"@"$ip":~

# Check if scp command was successful
if [ "$?" -eq 0 ]; then
  echo "File transferred successfully!"
else
  echo "File transfer failed."
fi
