#!/usr/bin/env bash

# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”
STRING="Hello World!"
# Don't forget to add a / to redirect_me:
REDIRECT="\n\tlocation = /redirect_me/ {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n\t}\n"
FILE="/etc/nginx/sites-available/default"

# Add the redirection rule to the Nginx configuration file
echo -e "$REDIRECT" >> "$FILE"

# Update the default Nginx server configuration
nginx -t && service nginx restart

# Replace the default index page content
echo "$STRING" > /var/www/html/index.nginx-debian.html
=======
# a script that installs Nginx server and /redirect_me
# to another page. With "301 Move Permanently" using
# the "1-install_nginx_web_server" script. 

# Update the package lists for upgrades and installs the Nginx server
sudo apt-get -y update
sudo apt-get -y install nginx

# Opens the HTTP (port 80) in the UFW firewall to allow Nginx traffic
sudo ufw allow 'Nginx HTTP'

# Writes the string to the /var/www/html/index file using sudo privileges
echo "Welcome to jostech.tech software solution provider!" | sudo tee /var/www/html/index

# Modifies the Nginx default server configuration file to add a rewrite rule that redirects
# requests for /redirect_me to https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanently
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;' /etc/nginx/sites-available/default

# Restarts the Nginx service to apply the changes made to the configuration
sudo service nginx restart
