#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”
STRING="Hello World!"
# Don't forget to add a / to redirect_me:
REDIRECT="\n\tlocation = /redirect_me/ {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n\t}\n"
FILE="/etc/nginx/sites-available/default"

# Add the redirection rule to the Nginx configuration file
echo -e "$REDIRECT" >> "$FILE"

# Update the default Nginx server configuration
nginx -t && service nginx restart

# Replace the default index page content
echo "$STRING" > /var/www/html/index.nginx-debian.html
