#!/usr/bin/env bash

# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”
STRING="Hello World!"

# Dont forget to add a / to redirect_me :
REDIRECT="\n\tlocation = /redirect_me/ {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n\t}\n"

FILE="/etc/nginx/sites-available/default"

sudo apt-get -y update

sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World" | sudo tee /var/www/html/index

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
