#!/usr/bin/env bash
# Parses Apache log files in list format.
#   Groups visitors by IP and HTTP status code.
#   Displays the number of occurrences, IP, and HTTP status
#+  code of each log, in sorted order.

#!/usr/bin/env bash
# Script that groups visitors by IP and HTTP status code, and displays this data.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
